services:
  mongo:
    image: mongo:7
    container_name: mongo-rs0
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 }).ok'"]
      interval: 5s
      timeout: 5s
      retries: 30

  mongo-init:
    image: mongo:7
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"
    entrypoint: ["bash", "-lc"]
    command: >
      '
      mongosh "mongodb://mongo:27017/admin" --quiet --eval "
        try {
          rs.status()
        } catch (e) {
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"localhost:27017\" }]
          })
        }
      "
      '

  mongo-express:
    image: mongo-express:1
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/?directConnection=true
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass

  mongo-tools:
    image: mongo:latest
    command: sleep infinity
    environment:
      MONGODB_URI: mongodb://mongo:27017/?directConnection=true
    depends_on:
      - mongo
    volumes:
      - ./data:/backups
      - ./scripts:/scripts

volumes:
  mongo_data: